### ISSUE TITLE
Static attention pattern

### ISSUE THREAD

**Issue by Bachstelze** [JacksonWuxs/Interpret_Instruction_Tuning_LLMs#2]
There is a static attention pattern in instruction-tuned decoders:
https://github.com/jessevig/bertviz/issues/128
You wrote that word pairs were obtained by interpreting parameters in the embedding space are redundant (see Chapter 5.1 on page 6 in version one of your paper). This statement could abrogate the discrepancy, yet it was omitted in the latest version. It is also feasible that most of the instruction verbs stand at the direct beginning of the instruction. And the static design has indeed the highest focus on the first token.
How do you explain your overworked results considering this pattern? Is the attention shift toward instruction verbs just a coincidence?

**Comment by JacksonWuxs** [comment]
Hi @Bachstelze, thanks for your questions! I believe your issue involves two questions. I will try to answer then respectively. 

**Q1: The interpretation of parameters in the embedding space could be redundant.** 
A1: This could be because of the nature of polysemantic [1] of deep neural networks. If you look closer at the results of self-attention heads by [2], you will find that its explanations (top-K word pairs) are typically only related to a single word. In our paper, we alleviate this negative impact of polysemantic by first considering neuron level explanation instead of head level compared to [2], also, introducing a local-context constraint during the construction of word-pairs. 

[1] Anthropic. "Towards Monosemanticity: Decomposing Language Models With Dictionary Learning." https://www.anthropic.com/news/towards-monosemanticity-decomposing-language-models-with-dictionary-learning. 2023.
[2] Dar, Guy, et al. "Analyzing transformers in embedding space." ACL. 2023.


**Q2: Whether the results focusing on instruction verbs can be simply explained as the instruction verbs usually lie in the beginning of the prompts?**
A2: We want to first highlight that our explanation method differs from the local explanation method, such as the bertviz for visualization of self-attention heads. Our proposed self-attention interpretation method does NOT utilize positional information,  meaning that the generated word-pairs explanations do not rely on the position of the given words. In addition, if you check Appendix B.3 of our latest version, you will find that the contribution of prompt tokens is distributed more uniformly after instruction tuning. Therefore, we believe that the shift toward instruction verbs is not an coincidence.
